name: "Setup WABT"
description: "Setup WebAssembly Binary Toolkit"
inputs:
  version:
    description: "Version to Install"
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Setup WABT
      shell: bash
      run: |
        set -e

        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = 'latest' ]; then
          VERSION=$(curl -sL "https://api.github.com/repos/WebAssembly/wabt/releases/latest" | jq -r '.tag_name')
        fi
        echo "Version: $VERSION"

        if [ "$RUNNER_OS" = 'Linux' ]; then
          ASSET=".*ubuntu.*\\\\.tar\\\\.gz$"
        elif [ "$RUNNER_OS" = 'macOS' ]; then
          ASSET=".*macos.*\\\\.tar\\\\.gz$"
        elif [ "$RUNNER_OS" = 'Windows' ]; then
          ASSET=".*windows.*\\\\.tar\\\\.gz$"
        else
          exit 1
        fi
        echo "Test: $ASSET"

        ASSET=$(curl -sL "https://api.github.com/repos/WebAssembly/wabt/releases/tags/$VERSION" | jq -r ".assets[].name | select(test(\"$ASSET\"))")
        echo "Asset: $ASSET"

        mkdir wabt
        curl -sL "https://github.com/WebAssembly/wabt/releases/download/$VERSION/$ASSET" | tar -xzC wabt --strip-components=1
        ls wabt/bin
        echo "$(pwd -W 2>/dev/null || pwd)/wabt/bin" >> $GITHUB_PATH
