name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        v: [canary, latest, 1.0.37]
    steps:
      - uses: actions/checkout@v3
      - name: Test Action
        uses: ./
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          version: ${{ matrix.v }}
      - name: Validate Success
        run: wasm2wat --version
